# Generated by Django 3.2 on 2021-06-09 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('swift_lyrics', '0004_auto_20210609_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyric',
            name='votes',
        ),
        migrations.AlterField(
            model_name='vote',
            name='lyric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='swift_lyrics.lyric'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
