# Generated by Django 3.2 on 2021-06-09 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swift_lyrics', '0005_auto_20210609_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='state',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
