# Generated by Django 3.2 on 2021-06-10 00:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swift_lyrics', '0007_auto_20210609_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, help_text="Album name - can alternatively use 'id' field set to id of existing album when creating new lyrics", unique=True)),
                ('first_year', models.IntegerField(help_text='First year active - debut year of the artist', null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2021)])),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.IntegerField(help_text='Release Year - year the album was released', null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2021)]),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(help_text='Artist - creator of the album', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='swift_lyrics.artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='collabs',
            field=models.ManyToManyField(help_text='Collabs - artist who collaborated on the creation of the album', null=True, related_name='collab_albums', to='swift_lyrics.Artist'),
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('name', 'artist')},
        ),
    ]
