# Generated by Django 3.2 on 2021-06-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swift_lyrics', '0008_auto_20210610_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='collabs',
            field=models.ManyToManyField(blank=True, help_text='Collabs - artists who collaborated on the creation of the album', related_name='collab_albums', to='swift_lyrics.Artist'),
        ),
    ]
