# Generated by Django 3.2 on 2021-06-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swift_lyrics', '0009_alter_album_collabs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.TextField(db_index=True, help_text="Album name - can alternatively use 'id' field set to id of existing album when creating new lyrics"),
        ),
    ]
