# Generated by Django 3.2 on 2021-06-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swift_lyrics', '0010_alter_album_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='album',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.UniqueConstraint(fields=('name', 'artist'), name='unique_album_name_per_artist'),
        ),
    ]
