# Generated by Django 3.2 on 2021-06-10 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swift_lyrics', '0011_auto_20210610_0334'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='album',
            name='unique_album_name_per_artist',
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('name', 'artist')},
        ),
    ]
